#! /usr/bin/env python2.7

from __future__ import print_function

import argparse
import sys

def die(msg):
    print("Test failed! Reason:", msg, file=sys.stderr)
    sys.exit(1)


def main(clang, shared_object, folder):
    print(clang, shared_object, folder)
    die("asd")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("clang",
            help="Path for clang program")
    parser.add_argument("shared_object",
            help="Full path to shared object to load")
    parser.add_argument("test_folder",
            help="Folder which contains an .in and .out file")
    args = parser.parse_args()

    main(args.clang, args.shared_object, args.test_folder)
